// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6sVy12i8bc_1Vebn0EfF1JTrG5AsGXIw',
    appId: '1:327247858547:web:f8156ebe6a178e0fba9306',
    messagingSenderId: '327247858547',
    projectId: 'stream-x-200b8',
    authDomain: 'stream-x-200b8.firebaseapp.com',
    storageBucket: 'stream-x-200b8.appspot.com',
    measurementId: 'G-KFNRS63SGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ46FIA9hWN5AAHxFdtBVrDgquaGkN-O4',
    appId: '1:327247858547:android:6cd7b213ee8b7fe1ba9306',
    messagingSenderId: '327247858547',
    projectId: 'stream-x-200b8',
    storageBucket: 'stream-x-200b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaS1o8wJ9PJq5BHlyeotrk-W9UhpM455E',
    appId: '1:327247858547:ios:03ae3ead38bcd30eba9306',
    messagingSenderId: '327247858547',
    projectId: 'stream-x-200b8',
    storageBucket: 'stream-x-200b8.appspot.com',
    iosClientId: '327247858547-s7muubnsqcrr2m6f9kefj448sa6lavbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.stream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaS1o8wJ9PJq5BHlyeotrk-W9UhpM455E',
    appId: '1:327247858547:ios:03ae3ead38bcd30eba9306',
    messagingSenderId: '327247858547',
    projectId: 'stream-x-200b8',
    storageBucket: 'stream-x-200b8.appspot.com',
    iosClientId: '327247858547-s7muubnsqcrr2m6f9kefj448sa6lavbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.stream',
  );
}
